### ISSUE TITLE
npm run dist, not working

### ISSUE THREAD

**Issue by Tech-no-logic-cat** [universalweb/Network#12]
---
name: Tech-no-logic-cat
about: electron builder
title: '"directories" in root is deprecated, please specify in the "build"'
labels: https://github.com/universalweb/Network/labels/bug
assignees: ''

---

**Describe the bug**
npm run dist would have to build the Appimage and snap files but instead it exit with error:
 "directories" in root is deprecated, please specify in the "build".

**To Reproduce**
in terminal execute npm run dist

**Expected behavior**
it creates Appimage and snap files
**Screenshots**
![image](https://user-images.githubusercontent.com/88969904/157652037-074a0194-5183-49b1-8c46-39890c0f612b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (unstable)

**Comment by tomekmarchi** [comment]
All older commands for a different API - if you notice the commits they are going to a specific directory.
