### ISSUE TITLE
[uwBridgw] Node.js version 

### ISSUE THREAD

**Issue by uwguide** [universalweb/Network#3]
Hello,

The [main package.json of the repo](https://github.com/universalweb/Network/blob/master/package.json#L66) states that the correct node.js version to use is >= 12.9.1 but while trying to installl dependencies for https://github.com/universalweb/Network/blob/master/uwBridge/package_Backup.json scrypt throws a compilation error. 

Quick search of my gyp build problems led me to https://github.com/axic/scrypt.js/issues/5 which confirms that not only I had problems trying to install scrypt on node.js 12.x.

I think it would be good to have specified version which works well for all UW projects so it's easier to test.

**Comment by tomekmarchi** [comment]
Anytime a file is labeled backup it's considered out of date and not to be used simply there for reference internally or for devs who want to keep track of or use older versions.
